---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install some fonts
  become: yes
  pacman:
    name: '{{ arch_fonts }}'
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Archlinux'
